import type { Metadata } from "next";
import '@/styles/global.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CookiesProvider } from "next-client-cookies";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
